# config/config.yaml

host: "https://reqres.in/api"
users: 3                  # Number of concurrent users (reduced for demo API)
spawn_rate: 1             # How fast users are spawned (users per second, reduced)
run_time: "1m"            # Total test duration (e.g., 30s, 1m, 5m)

endpoints:
  - path: "/api/users"
    method: "GET"
    weight: 3

  - path: "/api/users"
    method: "POST"
    weight: 2
    payload:
      name: "John Doe"
      job: "Engineer"

  - path: "/api/users/2"
    method: "GET"
    weight: 1
